In [12]:
import tensorflow as tf
import numpy as np

In [13]:
# Bước 1: Tạo vector, scalar, matrix và tensor với giá trị tùy chọn sử dụng `tf.constant()`
vector = tf.constant([1, 2, 3])  # Vector
scalar = tf.constant(5)         # Scalar
matrix = tf.constant([[1, 2], [3, 4]])  # Matrix
tensor = tf.constant(np.arange(24).reshape(2, 3, 4))  # Tensor

print("Vector:", vector)
print("Scalar:", scalar)
print("Matrix:", matrix)
print("Tensor:", tensor)

Vector: tf.Tensor([1 2 3], shape=(3,), dtype=int32)
Scalar: tf.Tensor(5, shape=(), dtype=int32)
Matrix: tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
Tensor: tf.Tensor(
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]], shape=(2, 3, 4), dtype=int32)


In [14]:

# Bước 2: Tìm shape, rank và size của tensor
shape = tensor.shape
rank = len(shape)
size = tf.size(tensor)

print("Shape:", shape)
print("Rank:", rank)
print("Size:", size)

Shape: (2, 3, 4)
Rank: 3
Size: tf.Tensor(24, shape=(), dtype=int32)


In [15]:
# Bước 3: Tạo hai tensor ngẫu nhiên
random_tensor1 = tf.random.uniform((5, 300), 0, 1)
random_tensor2 = tf.random.uniform((5, 300), 0, 1)

print("Random Tensor 1:", random_tensor1)
print("Random Tensor 2:", random_tensor2)

Random Tensor 1: tf.Tensor(
[[0.82550275 0.7143433  0.137218   ... 0.09596658 0.07404315 0.7722641 ]
 [0.9191344  0.41749108 0.74295557 ... 0.3058076  0.68560445 0.5919887 ]
 [0.69000447 0.9633348  0.7034426  ... 0.6977259  0.52627826 0.44681942]
 [0.49756324 0.34989858 0.12533212 ... 0.474671   0.20864773 0.2454443 ]
 [0.94863844 0.8140873  0.836058   ... 0.38005626 0.6396127  0.08763528]], shape=(5, 300), dtype=float32)
Random Tensor 2: tf.Tensor(
[[0.5718659  0.25860834 0.19689524 ... 0.7955363  0.87184846 0.7223711 ]
 [0.01936531 0.04040694 0.13996816 ... 0.3402058  0.7620131  0.13865602]
 [0.2642368  0.367298   0.07675469 ... 0.5217943  0.6000694  0.5337982 ]
 [0.42681098 0.46898746 0.11795056 ... 0.08069909 0.70532584 0.8071004 ]
 [0.609594   0.70789003 0.48500097 ... 0.24899888 0.6222007  0.6308849 ]], shape=(5, 300), dtype=float32)


In [16]:
# Bước 4: Nhân hai tensor với phép nhân ma trận
matrix_product = tf.matmul(random_tensor1, tf.transpose(random_tensor2))

print("Matrix Product:", matrix_product)


Matrix Product: tf.Tensor(
[[70.69924  69.54688  68.860634 70.88913  69.329926]
 [76.73995  75.27011  76.33292  73.56859  75.90292 ]
 [74.34935  73.8496   74.6493   69.33482  72.76921 ]
 [73.92499  72.26071  74.42119  70.00919  72.96648 ]
 [74.77965  70.87076  73.212135 71.76995  73.23956 ]], shape=(5, 5), dtype=float32)


In [17]:
# Bước 5: Nhân hai tensor với tích vô hướng
elementwise_product = random_tensor1 * random_tensor2
print("Elementwise Product:", elementwise_product)


Elementwise Product: tf.Tensor(
[[0.4720769  0.18473513 0.02701757 ... 0.07634489 0.06455441 0.55786127]
 [0.01779932 0.01686954 0.10399012 ... 0.10403752 0.52243954 0.08208279]
 [0.18232457 0.35383096 0.05399252 ... 0.3640694  0.31580347 0.23851141]
 [0.21236545 0.16409804 0.01478299 ... 0.03830552 0.14716463 0.1980982 ]
 [0.57828426 0.5762843  0.40548894 ... 0.09463359 0.39796746 0.05528777]], shape=(5, 300), dtype=float32)


In [18]:
# Bước 6: Tạo tensor ngẫu nhiên với shape (224, 224, 3)
random_image_tensor = tf.random.uniform((224, 224, 3), 0, 1)
print("Random Image Tensor:", random_image_tensor)

Random Image Tensor: tf.Tensor(
[[[0.7230201  0.49178147 0.25750458]
  [0.4612211  0.83165646 0.3308059 ]
  [0.68313503 0.19645631 0.9638616 ]
  ...
  [0.21848607 0.6563456  0.58488536]
  [0.19877064 0.60096395 0.96216154]
  [0.56231654 0.32975256 0.06108725]]

 [[0.37309134 0.30162394 0.30515277]
  [0.94500995 0.9931017  0.7545346 ]
  [0.80919504 0.38986492 0.93784666]
  ...
  [0.23471022 0.52597606 0.9500774 ]
  [0.4489571  0.47449017 0.84028244]
  [0.01899338 0.8370453  0.4914416 ]]

 [[0.8667611  0.7697444  0.9915787 ]
  [0.59512126 0.46568942 0.38351882]
  [0.259879   0.8193058  0.0897429 ]
  ...
  [0.68486476 0.37449157 0.7339834 ]
  [0.93596447 0.1505239  0.5448005 ]
  [0.97392607 0.37375915 0.89892805]]

 ...

 [[0.39289367 0.82721436 0.06717789]
  [0.02809489 0.8171276  0.36078072]
  [0.897622   0.8511009  0.33439493]
  ...
  [0.3472618  0.7733147  0.8758942 ]
  [0.33075666 0.5799135  0.54674816]
  [0.8457966  0.29437912 0.5451964 ]]

 [[0.9868922  0.5658854  0.4305805 ]
  [0.

In [19]:
# Bước 7: Tìm min và max của tensor
min_value = tf.reduce_min(random_image_tensor)
max_value = tf.reduce_max(random_image_tensor)

print("Min Value:", min_value)
print("Max Value:", max_value)

Min Value: tf.Tensor(1.3113022e-06, shape=(), dtype=float32)
Max Value: tf.Tensor(0.99998724, shape=(), dtype=float32)


In [20]:
# Bước 8: Tạo tensor với giá trị tuyệt đối và thay đổi shape
abs_tensor = tf.abs(random_image_tensor)
new_shape_tensor = tf.reshape(abs_tensor, (224, 224, 3))

print("Absolute Tensor:", abs_tensor)
print("New Shape Tensor:", new_shape_tensor)

Absolute Tensor: tf.Tensor(
[[[0.7230201  0.49178147 0.25750458]
  [0.4612211  0.83165646 0.3308059 ]
  [0.68313503 0.19645631 0.9638616 ]
  ...
  [0.21848607 0.6563456  0.58488536]
  [0.19877064 0.60096395 0.96216154]
  [0.56231654 0.32975256 0.06108725]]

 [[0.37309134 0.30162394 0.30515277]
  [0.94500995 0.9931017  0.7545346 ]
  [0.80919504 0.38986492 0.93784666]
  ...
  [0.23471022 0.52597606 0.9500774 ]
  [0.4489571  0.47449017 0.84028244]
  [0.01899338 0.8370453  0.4914416 ]]

 [[0.8667611  0.7697444  0.9915787 ]
  [0.59512126 0.46568942 0.38351882]
  [0.259879   0.8193058  0.0897429 ]
  ...
  [0.68486476 0.37449157 0.7339834 ]
  [0.93596447 0.1505239  0.5448005 ]
  [0.97392607 0.37375915 0.89892805]]

 ...

 [[0.39289367 0.82721436 0.06717789]
  [0.02809489 0.8171276  0.36078072]
  [0.897622   0.8511009  0.33439493]
  ...
  [0.3472618  0.7733147  0.8758942 ]
  [0.33075666 0.5799135  0.54674816]
  [0.8457966  0.29437912 0.5451964 ]]

 [[0.9868922  0.5658854  0.4305805 ]
  [0.7923

In [21]:
# Bước 9: Tạo tensor và tìm chỉ mục có giá trị lớn nhất
tensor_10 = tf.constant([3, 1, 4, 1, 5, 9, 2, 6, 5, 3])
argmax_index = tf.argmax(tensor_10)

print("Tensor 10:", tensor_10)
print("Argmax Index:", argmax_index)

Tensor 10: tf.Tensor([3 1 4 1 5 9 2 6 5 3], shape=(10,), dtype=int32)
Argmax Index: tf.Tensor(5, shape=(), dtype=int64)


In [22]:
# Bước 10: Mã hóa one-hot tensor
one_hot_encoded = tf.one_hot(argmax_index, depth=10)
print("One-Hot Encoded:", one_hot_encoded)

One-Hot Encoded: tf.Tensor([0. 0. 0. 0. 0. 1. 0. 0. 0. 0.], shape=(10,), dtype=float32)
